language: java
jdk: openjdk8

cache:
  directories:
    - $HOME/.m2

before_script:
  - psql -c 'create database troncwest' -U postgres
  - psql -c 'create role troncwest with login; grant all privileges on database troncwest to troncwest' -U postgres

branches:
  only:
    - dev
    - master

services:
  - postgresql